Add database
Panfilov50/java-filmorate pull request #5
Opened 2023-06-10 18:44 UTC by Panfilov50

2023-06-11 12:49 UTC, AnastasiyaFomkina requested changes

2023-06-11 12:49 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controllers/GenreController.java
> +    private final Logger log = (Logger) LoggerFactory.getLogger(GenreController.class);
Можно подключить логгер с помощью аннотации `@Slf4j`, как в контроллере фильмов

2023-06-11 12:49 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controllers/MpaController.java
> +    private final Logger log = (Logger) LoggerFactory.getLogger(MpaController.class);
И здесь тоже можно заменить на аннотацию `@Slf4j`

2023-06-11 12:49 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    public UserController(UserService userService) {
Лучше инжнктить с помощью [@RequiredArgsConstructor ](https://www.baeldung.com/spring-injection-lombok#:~:text=Constructor%20Injection%20With%20Lombok) из библиотеки `lombok`, так мы избавимся от однотипного кода

2023-06-11 12:49 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +        log.info("Post request {}", user);
Вся логика должна быть в сервисе, переделывать полностью UserController - не нужно.

2023-06-11 12:49 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
Нужно вернуть данный класс, он был реализован корректно

2023-06-11 12:49 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +import java.util.*;
_Саморазвитие_
В коммерческой разработке не принято использовать `wildcard` в импортах.
Вот отличная [статья](https://struchkov.dev/blog/using-wildcard-imports-in-java/) почему и как настроить идею, чтобы избавиться от `*`
Кстати, в IDEA есть отличное сочетание клавиш `Ctrl + Alt + O` - при нажатии сочетания в нужном классе автоматически оптимизируются импорты и удаляются ненужные

2023-06-11 12:49 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> -@RequiredArgsConstructor
Лучше инжектить через `@RequiredArgsConstructor`, чтобы избавиться от однотипного кода

2023-06-11 12:49 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        log.info("Запрос изменения фильма4");
Эти логи не соответствую действительности, их нужно удалить

2023-06-11 12:49 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        for (var film : films) {
Нужно заменить на [forEach](https://www.baeldung.com/foreach-java)

2023-06-11 12:49 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            for (var genre : film.getGenres()) {
Нужно заменить на [forEach](https://www.baeldung.com/foreach-java)

2023-06-11 12:49 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        likes.stream().filter(l -> l.getFilmId() == film.getId()).forEach(l -> likesByFilm.add(l.getUserId()));
Стримы принято бить по строкам, чтобы улучшить читаемости кода
```suggestion
        likes.stream()
            .filter(l -> l.getFilmId() == film.getId())
            .forEach(l -> likesByFilm.add(l.getUserId()));
```

Поправь для всех стримов в проекте

2023-06-11 12:49 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                                genres.stream().filter(g -> g.getId() == f.getGenreId()).findAny().get().getName())));
Прежде чем получать значение из `Optional` нужно убедиться, что он не пустой. Можно воспользоваться любым способом из [данной статьи](https://habr.com/ru/post/346782/#:~:text=%D0%9A%D0%B0%D0%BA%20%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B8%D1%82%D1%8C%20%D0%BE%D0%B1%D1%8A%D0%B5%D0%BA%D1%82%2C%20%D1%81%D0%BE%D0%B4%D0%B5%D1%80%D0%B6%D0%B0%D1%89%D0%B8%D0%B9%D1%81%D1%8F%20%D0%B2%20Optional%3F)

2023-06-11 12:49 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        film.getMpa().setName(mpaList.stream().filter(m -> m.getId() == film.getMpa().getId()).findAny().get().getName());
Нужно убедиться, что Optional не пуст

2023-06-11 12:49 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (film.getName() == null || film.getName().isEmpty() || film.getName().isBlank()) {
Все проверки ниже дублируют аннотации в модели `Film`, нужно их удалить

2023-06-11 12:49 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> -@RequiredArgsConstructor
Нужно вернуть

2023-06-11 12:49 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        for (var friend : friends) {
Нужно заменить на `forEach`

2023-06-11 12:49 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        for (var friendshipsByUser : friendshipsByUser1) {
Нужно заменить на `forEach`

2023-06-11 12:49 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        for (var friendshipsByUser : friendshipsByUser2) {
Нужно заменить на `forEach`

2023-06-11 12:49 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        for (var commonFriendId : friendIdByUser1) {
Нужно заменить на `forEach`

2023-06-11 12:49 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DBUserStorage.java
> +    private final Logger log = (Logger) LoggerFactory.getLogger(DBUserStorage.class);
Не используется, нужно удалить

2023-06-11 12:49 UTC, AnastasiyaFomkina commented on src/main/resources/application.properties
> +#spring.datasource.password=password
Все лишние параметры нужно удалить

2023-06-11 12:49 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/FilmTests.java
> +    final DBMpaStorage mpaStorage;
У полей класса должны быть модификаторы доступа

2023-06-11 12:49 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/FilmTests.java
> +        assertThat(updated).isNotNull();
Эти проверки повторяются выше, все однотипные ассерты нужно вынести в отдельный метод и переиспользовать их в тестах, а не писать дубли

2023-06-11 12:49 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/FriendsTest.java
> +        User user1 = userStorage.createUser(new User(1, "AAA@ya.ru", "AAA", "",
Создание однотипных сущностей для тестов нужно вынести либо в отдельный метод, либо в `@BeforeEach`

2023-06-11 12:49 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/FriendsTest.java
> +    final DBFriendsStorage friendsStorage;
Не хватает модификаторов доступа

2023-06-11 12:49 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/GenresTests.java
> +    final GenreStorage genreStorage;
Не хватает модификаторов доступа

2023-06-11 12:49 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/GenresTests.java
> +
Лишний отступ

2023-06-11 12:49 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/UserTests.java
> +    final DBUserStorage userStorage;
Не хватает модификаторов доступа

2023-06-11 12:49 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/ValidatorFilmTest.java
Тесты валидации нужно вернуть

2023-06-11 12:49 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/ValidatorUserTest.java
Тесты валидации нужно вернуть

2023-06-11 15:33 UTC, Panfilov50 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
После многократных попыток вернуть тесты, я начал писать проект заново в новом репозитории. После успешного возвращения тестов, оказалось что весь старый проект написан на другой версии java и тесты на нем не запускались. После починки всего этого (читай, создание с нуля) я создал пакет с ошибикой, данный класс не удален, просто пакет теперь называется /filmorate/controllers, а не /filmorate/controller как было раньше.

2023-06-12 16:26 UTC, AnastasiyaFomkina approved these changes
Работу принимаю, но все комментарии оставленные мной нужно будет исправить и проработать самостоятельно

2023-06-12 16:26 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                .forEach(l -> likesByFilm.add(l.getUserId()));
Если используешь стрим, лучше пользоваться терминальными операциями, которые собирают стрим в нужную коллекцию, например, в данном случае, можно сначала замаппить стрим лайков в стрим id лайков в помощью метода `.map`:
`.map(Likes::getUserId)`
и собрать его в сет с помощью терминального метода`.collect`:
`.collect(Collectors.toSet())`
Соответственно полный стрим будет выглядеть вот так:
```
Set<Integer> likesByFilm = likes.stream()
    .filter(l -> l.getFilmId() == film.getId())
    .map(Likes::getUserId)
    .collect(Collectors.toSet());
```

2023-06-12 16:26 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                .forEach(f -> genreByFilm.add(new Genres(f.getGenreId(),
Предлагаю собирать стрим в список с помощью терминальной операции `.collect`, пример можно посмотреть в комментарии ниже

2023-06-12 16:26 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            for (var genre : film.getGenres()) {
Здесь нужно использовать метод коллекции [forEach](https://www.baeldung.com/foreach-java)

2023-06-12 16:26 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (film.getName() == null || film.getName().isEmpty() || film.getName().isBlank()) {
Нужно удалить дублирующие проверки

2023-06-12 16:26 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        for (var friendshipsByUser : friendshipsByUser1) {
Нужно заменить на `forEach`

2023-06-12 16:26 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        for (var friendshipsByUser : friendshipsByUser2) {
Нужно заменить на `forEach`

2023-06-12 16:26 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        for (var commonFriendId : friendIdByUser1) {
Нужно переписать с помощью `stream api`, здесь больше подойдет `.map + .collect`, как в примерах выше

2023-06-19 07:25 UTC, merged